### ISSUE TITLE
Empty Expressions

### ISSUE THREAD

**Issue by sfkleach** [GetPoplog/Grammar#7]
Allow expressions to be empty, as per line 189 of [POPSYNTAX](https://github.com/GetPoplog/Grammar/blob/main/background/popsyntax) and introduce the non-terminal `NonEmptyExpression`. Use `NonEmptyExpression` to ensure the left-hand side of a FunctionApplication is non-empty. Simplify where appropriate.

## Acceptance Criteria

EBNF:
 - [ ] `Expression` may be empty
 - [ ] `FunctionApplication` left hand side is a non-empty expression
 - [ ] All uses of `Expression?` should be simplified as `Expression`

Identical criteria for Tabatkins grammar:
 - [ ] `Expression` may be empty
 - [ ] `FunctionApplication` left hand side is a non-empty expression
 - [ ] All uses of `Expression?` should be simplified as `Expression`

**Comment by edgardozoppi** [comment]
Now almost all existing uses of Expression have became NonEmptyExpression, except the usage for function arguments. This makes me consider doing the opposite thing of creating a new non-terminal PossibleEmptyExpression that is only used for function arguments and leave as Expression all the other usages that require a non-empty expression. I believe it feels more natural. What do you think?
